[project]
name = "django-movie-collection"
version = "0.1.0"
description = "A Django app for tracking a personal movie collection"
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "django-environ>=0.14.0",
    "gunicorn>=26.2.0",
    "waitress>=3.0.2",
    "whitenoise>=6.12.0",
]
