# Generated by Django 6.1.1 on 2026-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('watching', 'Watching'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='planned', max_length=20),
        ),
    ]
